# Generated by Django 3.2.15 on 2022-09-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220904_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, limit_choices_to={'font_type__lt': 2}, null=True, to='product.Category'),
        ),
    ]
