# Generated by Django 3.2.15 on 2022-08-24 13:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedetail',
            name='capacity_en',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attributedetail',
            name='capacity_ru',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attributedetail',
            name='capacity_uz',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attributedetail',
            name='consists_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='attributedetail',
            name='consists_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='attributedetail',
            name='consists_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='attributedetail',
            name='guarantee_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attributedetail',
            name='guarantee_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attributedetail',
            name='guarantee_uz',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attributedetail',
            name='made_in_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attributedetail',
            name='made_in_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attributedetail',
            name='made_in_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attributedetail',
            name='release_form_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attributedetail',
            name='release_form_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attributedetail',
            name='release_form_uz',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_en',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_ru',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug_uz',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_uz',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='typecategory',
            name='name_en',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='typecategory',
            name='name_ru',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='typecategory',
            name='name_uz',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
