# Generated by Django 3.2.15 on 2022-09-05 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_in_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='in_active',
            new_name='is_active',
        ),
    ]
