# Generated by Django 3.2.15 on 2022-09-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productimage_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='key',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
