# Generated by Django 3.2.15 on 2022-09-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='value',
            field=models.IntegerField(),
        ),
    ]
