# Generated by Django 3.2.15 on 2022-09-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20220912_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
