# Generated by Django 3.2.15 on 2022-09-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
