# Generated by Django 3.2.15 on 2022-09-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_sale'),
        ('cart', '0004_auto_20220919_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ManyToManyField(to='product.Product'),
        ),
    ]
