# Generated by Django 3.2.15 on 2022-09-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_product_sale'),
        ('cart', '0005_auto_20220919_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.quantityproduct'),
        ),
    ]
