# Generated by Django 3.2.15 on 2022-09-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220912_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Male'), (2, 'female')], default=0),
        ),
    ]
