# Generated by Django 3.2.15 on 2022-09-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='account',
            name='first_name_ru',
        ),
        migrations.RemoveField(
            model_name='account',
            name='first_name_uz',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name_ru',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name_uz',
        ),
    ]
